### ISSUE TITLE
Geocoding issues

### ISSUE THREAD

**Issue by jessyclubsoda** [club-soda/club-soda-guide#653] opened 2020-01-03 12:59 UTC
Over the past week or so, we've been getting this notification on every venue page on the site across multiple devices meaning that the Google Maps location doesn't load

![Geocode issue](https://user-images.githubusercontent.com/49029914/71724574-a466ee00-2e28-11ea-9b5e-8cece86aa2fe.png)

Any ideas what might be going on?

**Comment by nelsonic** [comment] 2020-01-03 17:33
Oh ... This seems like an it's an issue with the Google Maps API Key. 💭
Thanks for opening the issue @jessyclubsoda 👍 
@SimonLab do you have time to investigate this on Monday morning? 🔍

**Comment by SimonLab** [comment] 2020-01-06 10:52
I've checked that the API key wasn't linked to one of the developer account (ie a temporary key) and it looks like Club Soda did create the key see https://github.com/club-soda/club-soda-guide/issues/6 

I'm not sure why the key is not valid anymore, my first guess is that the free trial account might have ended but it can be another issue.

@jessyclubsoda @jussi-club-soda could you check if the API key still exist on your account otherwise you might need to create a new one.
You should be able to access the API and services from https://console.cloud.google.com/ however I don't know which email/account was used to create the key.

Steps to create a new key if the current one is not found:
https://github.com/club-soda/club-soda-guide/issues/6#issuecomment-447182412

**Comment by jussi-club-soda** [comment] 2020-01-06 11:22
Yes, looks like we had a free trial account which has ended - I've "upgraded" our account, the APIs are still on the Google Console, I'm just seeing this:

! Remember to configure the OAuth consent screen with information about your application.

which gives me two options:

OAuth consent screen
Choose how you want to configure and register your app, including your target users. You can only associate one app with your project.
User Type
Internal
Only available to users within your organisation. You will not need to submit your app for verification.
External
Available to any user with a Google Account.

What should I do here?

**Comment by nelsonic** [comment] 2020-01-06 11:45
@jussi-club-soda it might be an idea for us to have a Zoom call to get this resolved.
Please let us know your availability today/tomorrow. 
Thanks!

**Comment by jussi-club-soda** [comment] 2020-01-06 12:54
@nelsonic I think the maps are now working again. Happy to have a chat to discuss anything else we may need to do on Google to make sure things keep on working! I'm free this afternoon, but away all day tomorrow.

**Comment by nelsonic** [comment] 2020-01-07 08:02
@jussi-club-soda thanks for confirming that Google Maps is working again! 🎉 
Provided you have the API keys setup and under control, it should work without any issues now.
We've had apps using Google Maps in production for several years without needing to update the keys.

@jessyclubsoda once you have confirmed everything is working, please let us know (_and close the issue_).
Thanks! 👍

**Closed** 2020-01-08 11:12 UTC
Labels: bug, please-test
