### ISSUE TITLE
Use my location in Search Bar

### ISSUE THREAD

**Issue by ctrembath** [club-soda/club-soda-guide#231] opened 2018-12-13 13:22 UTC
As a customer looking at the homepage,
I would like to click 'use my location' in the search bar
so I can find venues close to me

@iteles can you confirm this feature will be added to the Search Bar?

## Acceptance Criteria
- [x] Homepage hero section Search bar includes 'Use My Location' CTA
  - [x] Mobile includes the icon in [this comment](https://github.com/club-soda/club-soda-guide/issues/231#issuecomment-449026444) in lieu of the 'Use My Location' wording
- [x] Clicking 'Use My Location' takes user to search results page
- [x] Search results show venues ordered by distance from location

## Screenshot
![screenshot 2018-12-13 at 13 17 54](https://user-images.githubusercontent.com/8418748/49941149-9242a680-fed9-11e8-8323-4c16f392d873.png)

**Comment by iteles** [comment] 2018-12-13 18:18
@ctrembath Yes, this one is a duplicate of https://github.com/club-soda/club-soda-guide/issues/6 (though this one is great as it has much more detail so we should go ahead and either add the detail to the original or close the original in favour of this one!).

It's sitting a bit further down in the prioritised sprint backlog than you have put this issue though, so I'm not sure whether it was the question or the feature that was high priority:
![image](https://user-images.githubusercontent.com/4185328/49958681-73590a00-ff03-11e8-88e1-e1af7a0ccfa2.png)

**Comment by ctrembath** [comment] 2018-12-18 11:14
OK great thanks for explaining,

The "Find Venues Near Me" button seems to currently feature throughout the platform, however the 'Use My Location' within the search bar hasn't yet been added.

In the card #129 it only mentions the 'Find Venues Near Me' CTA. This card refers specifically to the  'Use My Location' CTA within the Search bar.

Do you consider this issue and #129  the same item?

**Comment by ctrembath** [comment] 2018-12-18 14:41
Hi @iteles - yes we user tested the 'Use my location' feature with @harrygfox.

See [here](https://github.com/club-soda/club-soda-guide/blob/02e752ebb72e847b41cc02b0af7287840bca296c/design/post-testing-mockup.png) for his mockup he made based on the user testing

**Comment by ctrembath** [comment] 2018-12-20 09:38
@iteles you're right - we haven't user tested the wording here.

My assumption is that 'Use my location' makes the most sense - however, having had a look around at how other sites do it, it seems the hero section search bar differs hugely from site to site.

I think for now we keep the 'Use my location' CTA within the search bar, and once the guide is being used, we can review how the search bar is being used.

I have a suspicious that users will type the name of an area OR a postcode into the search bar - how do you plan to handle this input?

**Comment by ctrembath** [comment] 2018-12-20 14:59
@iteles Attached is an icon to replace the 'Use My Location'  on mobile


![mylocation](https://user-images.githubusercontent.com/8418748/50291987-e7e1fa80-0467-11e9-85a0-21a6d5511c3b.png)

**Comment by RobStallion** [comment] 2019-01-03 14:09
@ctrembath @jussi-club-soda

with regards to the following point...

Search results show venues ordered by distance from location

Do you still want the club soda score to have an impact or do you only want it sorted by distance? (for example would you want all venues with a club soda score of 5 sorted by distance, then the same for the 4s etc)

Also do you want to display all venues when searching using location? Currently the function I'm working on checks for venues within a 5km radius and if there are none checks again for any within a 10km radius. It repeats these steps up to 30km away. I didn't think we would need to display a bar in Glasgow for example if a user is on central London.

It's a comment I am writing to club soda. Just want to see if that makes sense to you and get your thoughts on it

**Comment by jussi-club-soda** [comment] 2019-01-03 14:18
If possible, it would be good to use the score as well as distance, since we want to highlight the best venues.

Also agree it should have a cut-off point in terms of distance.

Not 100% sure how to balance the two factors without making it overly complicated... Maybe look for 3 to 5 star venues first, and if there are none, then list 0 to 2 star venues?

**Comment by ctrembath** [comment] 2019-01-11 11:30
Once i've clicked the 'Use my location' button it takes about 3 seconds to direct me to the Search Results page and doesn't indicate that results are being processed in the background. Is there something we could do to make it clear to the user that it is loading ... perhaps making the 'Use my location' button disabled?

**Closed** 2019-01-25 16:07 UTC
Labels: please-test, priority-2
