### ISSUE TITLE
DryDrinker & WiseBartender links

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#217] opened 2018-12-11 14:55 UTC
For two online shops: drydrinker.com (DD) and wisebartender.co.uk (WB), we currently do not have affiliate links; instead people need to type in a discount code (clubsodavip for both) to get a 5% discount - and for all of these purchases, we also get a 5% fee of the sale total. 

Acceptance criteria:
- [x] for drink brands that are sold at DD and WB online shops, display a link to DD and WB websites on drink brand profile pages
- [x] also display in some way "Use discount code CLUBSODAVIP" or similar wording to let customers know about the discount available to them
- [x] the links can direct to the DD / WB home pages (less preferable), or to the individual brand / drink pages at their websites (more preferable)
- [x] admins to have the ability to create these links, and to turn them on for drinks we know are sold at DD and WB (and to turn them off as well)

**Comment by Cleop** [comment] 2019-01-03 08:22
@jussi-club-soda - regarding the discount codes, could you confirm/clarify the following:
- will there be just one discount code per brand (DD and WB only)?
- would you like the code itself to be editable by the admin? (rather than hard coded by us)

**Comment by jussi-club-soda** [comment] 2019-01-06 18:09
Yes, just one discount code per brand (it just happens to be the same for those two!)

And yes, it would be helpful for admins to be able to edit the codes!

**Comment by Cleop** [comment] 2019-01-16 10:42
This is what I currently have:
![image](https://user-images.githubusercontent.com/16775804/51243586-d878a300-197a-11e9-94f7-43b6e5d2e550.png)
The designs feature this 'i' icon:
<img src="https://user-images.githubusercontent.com/16775804/51243736-30afa500-197b-11e9-89af-62f217f64ae3.png" width=150px />

I don't know if anyone else has strong feelings but to me I'm not sure that the 'i' adds any value to the user aside from a bit more visual clutter. I think the background colour and code stand out enough. I also don't think I associate 'i' aka 'info' with a discount code.

@iteles @jussi-club-soda

**Comment by iteles** [comment] 2019-01-16 16:38
@Cleop I agree with your assessment here personally - I would suggest we make the code bold and remove the 'i' which is superfluous.

**Comment by ctrembath** [comment] 2019-01-25 15:56
The discount code information isn't showing for Heineken on staging. See screenshot
![screenshot 2019-01-25 at 15 55 24](https://user-images.githubusercontent.com/8418748/51756779-b806c200-20b9-11e9-84e7-7127f6a3837c.png)

**Comment by Cleop** [comment] 2019-01-28 16:04
I believe this bug has been caused by the same issue as in #420 regarding the change from retailers being plural to singular as when I add a discount code on the branch with those changes it now works:

![image](https://user-images.githubusercontent.com/16775804/51848874-5e4f0380-2316-11e9-9c2e-5992133f2b8c.png)

I will update the labels on this issue once that PR has been merged.

**Comment by ctrembath** [comment] 2019-02-01 08:45
I'm not seeing the 'Discount Code' information on staging
![screenshot 2019-02-01 at 08 44 05](https://user-images.githubusercontent.com/8418748/52112187-b1b69f80-25fd-11e9-90a4-d1a325ee70f1.png)

**Comment by Cleop** [comment] 2019-02-01 09:10
That's because there were no discount codes or the DryDrinker/Wisebartender retailers created. The codes/retailers may have been deleted when the staging data was reduced recently. I've just added the retailers and a discount code to one of them:

![image](https://user-images.githubusercontent.com/16775804/52113380-0a3b6c00-2601-11e9-924d-ffffb6e94297.png)

**Closed** 2019-02-01 17:57 UTC
Labels: please-test
