### ISSUE TITLE
Wrong drink images displayed

### ISSUE THREAD

**Issue by jussi-club-soda** [club-soda/club-soda-guide#239] opened 2018-12-13 17:17 UTC
The drink images sometimes display the wrong one - for example just now I got these two different views when looking for Ghost Ship:

![ghost-1](https://user-images.githubusercontent.com/43003062/49955485-ce3a3380-fefa-11e8-85b2-1f3232565416.jpg)
![ghost-2](https://user-images.githubusercontent.com/43003062/49955487-ced2ca00-fefa-11e8-8aef-6670a72016d0.jpg)

**Comment by jussi-club-soda** [comment] 2018-12-14 13:41
Not the first time, and other people have noticed it too...

**Comment by Danwhy** [comment] 2018-12-14 13:45
:+1: I have managed to briefly reproduce it myself once; something to do with flipping the card then searching. Not 10% sure how to reproduce again, but I'll keep looking into it

**Comment by Danwhy** [comment] 2018-12-14 13:56
I think this is to do with the images sometimes not loading fast enough, because there are so many of them.

What I've seen is that if I search quickly after the page loads, the images will briefly be wrong, but will eventually change after a few seconds. Does that sound similar to what you've experienced @jussi-club-soda? If so, I'll look into the way images are rendered and try to make some improvements so it doesn't happen any more.

**Comment by jussi-club-soda** [comment] 2018-12-14 14:04
It could be to do with loading - not 100% sure but it may be that these disappear with time...

**Comment by iteles** [comment] 2019-01-25 16:25
This is still an issue (see #419, closed as duplicate) , bumping the priority:
![image](https://user-images.githubusercontent.com/4185328/51758482-b63efd80-20bd-11e9-969e-a2a765669913.png)

**Comment by Danwhy** [comment] 2019-01-30 11:32
This is definitely due to the images not loading fast enough, as now that there are more images, it's happening even more frequently, and the images are appearing in the order they are first loaded in. I'm going to put a few hours into investigating ways to optimise the image loading.

**Comment by nelsonic** [comment] 2019-01-30 11:41
@Danwhy time to _optimise_ the images using a Lambda function after they are uploaded?

**Comment by Danwhy** [comment] 2019-01-30 11:56
@nelsonic That would probably help somewhat, but I think the main problem is within the code right now.

The drinks are all always being stored in the model, then filtered as they are rendered. Filtering them as the search is happening and updating the model, then rendering all remaining images in the model would be better, and should stop this issue from happening.

I'll fix this issue first, then we can look into optimising the images themselves.

**Comment by nelsonic** [comment] 2019-01-30 12:46
@DanWhy makes sense. Thanks for confirming. 👍🏻

**Comment by Danwhy** [comment] 2019-01-30 12:52
After looking into it a little more and attempting to implement my solution, it seems that the problem isn't so much the images themselves, but just the number of items. 

On my local version where the images don't actually exist except for the default one (which is only 4kb so definitely doesn't load slowly), the same problem happens.

<img width="500" alt="screen shot 2019-01-30 at 12 50 37" src="https://user-images.githubusercontent.com/8939909/51982386-c3793500-248d-11e9-896a-fd152683726d.png">
<img width="400" alt="screen shot 2019-01-30 at 12 51 03" src="https://user-images.githubusercontent.com/8939909/51982394-c70cbc00-248d-11e9-9b8a-c56599bf9516.png">

I think the best solution would be to implement 'lazy rendering', where we only render some of the results, and render more if the user scrolls to the bottom of the page. If you try searching on the live site after filtering to 'spirits & mixers' you'll see that this problem doesn't occur, so 40 items seems to be a good amount.

**Comment by ctrembath** [comment] 2019-02-01 08:33
I'm not able to test this on staging - Do you think paginating the results would be the most reliable way to handle all the images needing to load?

**Closed** 2019-04-02 15:22 UTC
Labels: T1h, T2h, bug, please-test, priority-2, question
